create table if not exists public.settings (
  id bigint primary key default 1,
  shop_name text not null default 'RAHMAN XEROX & SIFY IWAY',
  shop_email text default 'ammaporur@gmail.com',
  shop_phone text default '',
  shop_address text default '',
  bill_prefix text not null default 'RX-',
  starting_number integer not null default 1,
  default_customer text not null default 'Walk-in Customer',
  receipt_paper_size text not null default 'thermal',
  printer_name text default '',
  show_email_on_receipt integer not null default 1,
  show_customer_on_receipt integer not null default 1,
  pin_enabled integer not null default 0,
  pin_code text default '',
  theme text not null default 'light',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  mobile text,
  email text,
  total_bills integer not null default 0,
  total_spent numeric not null default 0,
  last_visit timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  bill_number text not null unique,
  customer_id bigint references public.customers(id),
  customer_name text,
  customer_mobile text,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  payment_method text not null default 'cash',
  cash_amount numeric not null default 0,
  upi_amount numeric not null default 0,
  card_amount numeric not null default 0,
  other_amount numeric not null default 0,
  status text not null default 'COMPLETED',
  void_reason text,
  voided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.bills(id) on delete cascade,
  service_id bigint,
  service_name_snapshot text not null,
  category_name_snapshot text,
  quantity numeric not null default 1,
  rate numeric not null,
  amount numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.service_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null default 0,
  is_active integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  category_id bigint references public.service_categories(id),
  name text not null,
  unit text not null default 'piece',
  default_rate numeric not null default 0,
  min_rate numeric not null default 0,
  is_active integer not null default 1,
  is_custom integer not null default 0,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_price_options (
  id bigint generated by default as identity primary key,
  service_id bigint not null references public.services(id) on delete cascade,
  rate numeric not null,
  is_default integer not null default 0,
  label text,
  created_at timestamptz not null default now()
);

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category_id bigint references public.expense_categories(id),
  name text not null,
  amount numeric not null default 0,
  payment_method text not null default 'cash',
  notes text,
  expense_date date not null default current_date,
  created_at timestamptz not null default now()
);

insert into public.service_categories (name, display_order) values
  ('Xerox', 0), ('Printout', 1), ('ID Card', 2), ('Lamination', 3), ('Scanning', 4),
  ('Photo', 5), ('Binding', 6), ('Online Services', 7), ('Government Services', 8), ('Other', 9)
on conflict (name) do nothing;

insert into public.expense_categories (name) values
  ('Paper'), ('Ink/Toner'), ('Electricity'), ('Stationery'), ('Rent'), ('Maintenance'), ('Other')
on conflict (name) do nothing;

insert into public.services (category_id, name, unit, default_rate, min_rate)
select c.id, s.name, s.unit, s.default_rate, s.min_rate
from (values
  ('Xerox', 'A4 B/W Single Side', 'page', 2::numeric, 2::numeric),
  ('Xerox', 'A4 B/W Front & Back', 'page', 3, 3),
  ('Xerox', 'A4 Color Single Side', 'page', 10, 10),
  ('Xerox', 'A4 Color Front & Back', 'page', 15, 15),
  ('Xerox', 'A3 B/W Single Side', 'page', 10, 10),
  ('Xerox', 'A3 B/W Front & Back', 'page', 20, 20),
  ('Xerox', 'A3 Color Single Side', 'page', 30, 30),
  ('Xerox', 'A3 Color Front & Back', 'page', 60, 60),
  ('Xerox', 'ID Card B/W', 'copy', 4, 4),
  ('Xerox', 'ID Card Color', 'copy', 10, 10),
  ('Xerox', 'DL / Smart Card Duplicate', 'service', 80, 80),
  ('Printout', 'B/W Single Side', 'page', 3, 3),
  ('Printout', 'B/W Front & Back', 'page', 2.5, 2.5),
  ('Printout', 'Color Single Side', 'page', 10, 10),
  ('Printout', 'Color Front & Back', 'page', 15, 15),
  ('Lamination', 'A4 Lamination', 'piece', 35, 35),
  ('Lamination', 'A3 Lamination', 'piece', 70, 70),
  ('Lamination', 'A5 Lamination', 'piece', 20, 20),
  ('Lamination', 'ID Card Lamination', 'piece', 20, 10),
  ('Scanning', 'B/W Scan', 'page', 6, 6),
  ('Scanning', 'Color Scan', 'page', 10, 10),
  ('Photo', 'Passport Photo - 8 Copies', 'set', 80, 80),
  ('Binding', 'Soft Binding', 'service', 30, 30),
  ('Binding', 'Spiral Binding', 'service', 40, 40),
  ('Online Services', 'Online Service', 'service', 350, 200),
  ('Online Services', 'Email / Document Send', 'service', 10, 10),
  ('Government Services', 'Aadhaar Address Update', 'service', 50, 50),
  ('Government Services', 'PAN Card Service', 'service', 260, 260),
  ('Government Services', 'TNEGA Community Certificate', 'service', 260, 260),
  ('Government Services', 'TNEGA Income Certificate', 'service', 260, 260),
  ('Government Services', 'TNEGA OBC Certificate', 'service', 260, 260),
  ('Government Services', 'TNEGA Nativity Certificate', 'service', 260, 260),
  ('Government Services', 'TNEGA First Graduate Certificate', 'service', 360, 360),
  ('Government Services', 'TNEGA Legal Heir Certificate', 'service', 360, 360),
  ('Government Services', 'Passport Service', 'service', 300, 300),
  ('Other', 'Custom Service', 'custom', 0, 0)
) as s(category_name, name, unit, default_rate, min_rate)
join public.service_categories c on c.name = s.category_name
where not exists (select 1 from public.services existing where existing.name = s.name);

insert into public.service_price_options (service_id, rate, is_default)
select s.id, s.default_rate, 1
from public.services s
where not exists (select 1 from public.service_price_options option where option.service_id = s.id);

drop policy if exists "public app access settings" on public.settings;
drop policy if exists "public app access customers" on public.customers;
drop policy if exists "public app access bills" on public.bills;
drop policy if exists "public app access bill items" on public.bill_items;
drop policy if exists "public app access service categories" on public.service_categories;
drop policy if exists "public app access services" on public.services;
drop policy if exists "public app access service options" on public.service_price_options;
drop policy if exists "public app access expense categories" on public.expense_categories;
drop policy if exists "public app access expenses" on public.expenses;

alter table public.settings enable row level security;
alter table public.customers enable row level security;
alter table public.bills enable row level security;
alter table public.bill_items enable row level security;
alter table public.service_categories enable row level security;
alter table public.services enable row level security;
alter table public.service_price_options enable row level security;
alter table public.expense_categories enable row level security;
alter table public.expenses enable row level security;

create policy "public app access settings" on public.settings for all using (true) with check (true);
create policy "public app access customers" on public.customers for all using (true) with check (true);
create policy "public app access bills" on public.bills for all using (true) with check (true);
create policy "public app access bill items" on public.bill_items for all using (true) with check (true);
create policy "public app access service categories" on public.service_categories for all using (true) with check (true);
create policy "public app access services" on public.services for all using (true) with check (true);
create policy "public app access service options" on public.service_price_options for all using (true) with check (true);
create policy "public app access expense categories" on public.expense_categories for all using (true) with check (true);
create policy "public app access expenses" on public.expenses for all using (true) with check (true);

insert into public.settings (id) values (1) on conflict (id) do nothing;

-- Grant the app roles access to all tables (newer Supabase projects do not
-- auto-grant permissions for tables created via SQL scripts).
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;
