create table if not exists public.settings (
  id bigint primary key default 1,
  shop_name text not null default 'RAHMAN XEROX & SIFY IWAY',
  shop_email text default 'ammaporur@gmail.com',
  shop_phone text default '',
  shop_address text default '',
  bill_prefix text not null default 'RX-',
  starting_number integer not null default 1,
  default_customer text not null default 'Walk-in Customer',
  receipt_paper_size text not null default 'thermal',
  printer_name text default '',
  show_email_on_receipt integer not null default 1,
  show_customer_on_receipt integer not null default 1,
  pin_enabled integer not null default 0,
  pin_code text default '',
  theme text not null default 'light',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  mobile text,
  email text,
  total_bills integer not null default 0,
  total_spent numeric not null default 0,
  last_visit timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  bill_number text not null unique,
  customer_id bigint references public.customers(id),
  customer_name text,
  customer_mobile text,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  payment_method text not null default 'cash',
  cash_amount numeric not null default 0,
  upi_amount numeric not null default 0,
  card_amount numeric not null default 0,
  other_amount numeric not null default 0,
  status text not null default 'COMPLETED',
  void_reason text,
  voided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint not null references public.bills(id) on delete cascade,
  service_id bigint,
  service_name_snapshot text not null,
  category_name_snapshot text,
  quantity numeric not null default 1,
  rate numeric not null,
  amount numeric not null,
  created_at timestamptz not null default now()
);

alter table public.settings enable row level security;
alter table public.customers enable row level security;
alter table public.bills enable row level security;
alter table public.bill_items enable row level security;

create policy "public app access settings" on public.settings for all using (true) with check (true);
create policy "public app access customers" on public.customers for all using (true) with check (true);
create policy "public app access bills" on public.bills for all using (true) with check (true);
create policy "public app access bill items" on public.bill_items for all using (true) with check (true);

insert into public.settings (id) values (1) on conflict (id) do nothing;
